name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore RealEstate

      - name: Build solution
        run: dotnet build RealEstate --no-restore

      - name: Run unit tests on Business Logic Layer
        run: dotnet test RealEstate/RealEstate.BLLTests --no-build --verbosity normal

      - name: Run Integration Tests
        run: dotnet test RealEstate/RealEstate.API.IntegrationTests --no-build --verbosity normal
